[features]
seeds = true
skip-lint = false
[programs.localnet]
calculator = "6Et5YsqS2LiMefFmf7iwQ2L2vmxmrzHHJeeuH12Nboou"
[programs.devnet]
calculator = "6Et5YsqS2LiMefFmf7iwQ2L2vmxmrzHHJeeuH12Nboou"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "devnet"
wallet = "/home/nico/.config/solana/devnet-id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
